/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jScope_LocalDataProvider */

#ifndef _Included_jScope_LocalDataProvider
#define _Included_jScope_LocalDataProvider
#ifdef __cplusplus
extern "C" {
#endif
#undef jScope_LocalDataProvider_RESAMPLE_TRESHOLD
#define jScope_LocalDataProvider_RESAMPLE_TRESHOLD 1000000000i64
#undef jScope_LocalDataProvider_MAX_PIXELS
#define jScope_LocalDataProvider_MAX_PIXELS 2000L
/*
 * Class:     jScope_LocalDataProvider
 * Method:    NativeisSegmentedNode
 * Signature: (Ljava/lang/String;)Z
 */
  JNIEXPORT jboolean JNICALL Java_local_localDataProvider_NativeisSegmentedNode
      (JNIEnv *, jclass, jstring);

/*
 * Class:     jScope_LocalDataProvider
 * Method:    NativegetSegment
 * Signature: (Ljava/lang/String;II)[B
 */
  JNIEXPORT jbyteArray JNICALL Java_local_localDataProvider_NativegetSegment
      (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     jScope_LocalDataProvider
 * Method:    NativegetAllFrames
 * Signature: (Ljava/lang/String;II)[B
 */
  JNIEXPORT jbyteArray JNICALL Java_local_localDataProvider_NativegetAllFrames
      (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     jScope_LocalDataProvider
 * Method:    NativegetInfo
 * Signature: (Ljava/lang/String;Z)[I
 */
  JNIEXPORT jintArray JNICALL Java_local_localDataProvider_NativegetInfo
      (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     jScope_LocalDataProvider
 * Method:    NativegetSegmentTimes
 * Signature: (Ljava/lang/String;Ljava/lang/String;FF)[F
 */
  JNIEXPORT jfloatArray JNICALL Java_local_localDataProvider_NativegetSegmentTimes
      (JNIEnv *, jclass, jstring, jstring, jfloat, jfloat);

/*
 * Class:     jScope_LocalDataProvider
 * Method:    NativegetAllTimes
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[F
 */
  JNIEXPORT jfloatArray JNICALL Java_local_localDataProvider_NativegetAllTimes
      (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     jScope_LocalDataProvider
 * Method:    NativegetSegmentIdxs
 * Signature: (Ljava/lang/String;FF)[I
 */
  JNIEXPORT jintArray JNICALL Java_local_localDataProvider_NativegetSegmentIdxs
      (JNIEnv *, jclass, jstring, jfloat, jfloat);

/*
 * Class:     jScope_LocalDataProvider
 * Method:    NativeSetEnvironmentSpecific
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
  JNIEXPORT void JNICALL Java_local_localDataProvider_NativeSetEnvironmentSpecific
      (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     jScope_LocalDataProvider
 * Method:    NativeUpdate
 * Signature: (Ljava/lang/String;J)V
 */
  JNIEXPORT void JNICALL Java_local_localDataProvider_NativeUpdate
      (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     jScope_LocalDataProvider
 * Method:    NativeGetString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
  JNIEXPORT jstring JNICALL Java_local_localDataProvider_NativeGetString(JNIEnv *, jobject, jstring);

/*
 * Class:     jScope_LocalDataProvider
 * Method:    NativeGetFloat
 * Signature: (Ljava/lang/String;)D
 */
  JNIEXPORT jdouble JNICALL Java_local_localDataProvider_NativeGetFloat
      (JNIEnv *, jobject, jstring);

/*
 * Class:     jScope_LocalDataProvider
 * Method:    NativeGetLongArray
 * Signature: (Ljava/lang/String;)[J
 */
  JNIEXPORT jlongArray JNICALL Java_local_localDataProvider_NativeGetLongArray
      (JNIEnv *, jobject, jstring);

/*
 * Class:     jScope_LocalDataProvider
 * Method:    NativeGetFloatArray
 * Signature: (Ljava/lang/String;)[F
 */
  JNIEXPORT jfloatArray JNICALL Java_local_localDataProvider_NativeGetFloatArray
      (JNIEnv *, jobject, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetDoubleArray
 * Signature: (Ljava/lang/String;)[D
 */
  JNIEXPORT jdoubleArray JNICALL Java_local_localDataProvider_NativeGetDoubleArray
      (JNIEnv *, jobject, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetIntArray
 * Signature: (Ljava/lang/String;)[I
 */
  JNIEXPORT jintArray JNICALL Java_local_localDataProvider_NativeGetIntArray(JNIEnv *, jobject, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeGetByteArray
 * Signature: (Ljava/lang/String;)[B
 */
  JNIEXPORT jbyteArray JNICALL Java_local_localDataProvider_NativeGetByteArray
      (JNIEnv *, jobject, jstring);

/*
 * Class:     local_localDataProvider
 * Method:    NativeErrorString
 * Signature: ()Ljava/lang/String;
 */
  JNIEXPORT jstring JNICALL Java_local_localDataProvider_NativeErrorString(JNIEnv *, jobject);

/*
 * Class:     local_localDataProvider
 * Method:    NativeregisterEvent
 * Signature: (Ljava/lang/String;I)I
 */
  JNIEXPORT jint JNICALL Java_local_localDataProvider_NativeregisterEvent
      (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     local_localDataProvider
 * Method:    NativeunregisterEvent
 * Signature: (I)V
 */
  JNIEXPORT void JNICALL Java_local_localDataProvider_NativeunregisterEvent(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
